apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ds5cddhh9-nodejs
  janus-idp.io/tekton: ds5cddhh9-nodejs
  backstage.io/kubernetes-id: ds5cddhh9-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ds5cddhh9-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
